language: go
go:
  - 1.20.x

service:
  - docker

git:
  depth: 1

env:
  global:
    - USER="okpalaChidiebere"
    - DOCKER_USERNAME="aluminetchidiebre"
    - SERVICE_NAME="chirper-app-user-service"
    - GOPRIVATE="github.com/${USER}"
    # --mount flag we used in our Dockerfile required BuildKit. documentation https://docs.docker.com/build/buildkit/#getting-started
    - DOCKER_BUILDKIT=1

# Pre-testing installs
before_install:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" > $HOME/.netrc
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.52.2

install:
  - echo "nothing needs to be installed; skipping..."

script:
  # if i don't override the default bash script `travis_script_go.bash` that travis run during this stage our test will be ran twice
  - echo "skipping before_script step..."

before_deploy:
  - golangci-lint run --disable errcheck
  - go test -v -race ./...

# if the script in the `before_deploy` this step will not run
deploy:
  provider: script
  script: docker --version;
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
    docker build --secret id=gitcredentials,src=$HOME/.netrc -t "$DOCKER_USERNAME"/"$SERVICE_NAME":"$TRAVIS_BUILD_ID" --build-arg GOPRIVATE=$GOPRIVATE .;
    docker images;
    docker push "$DOCKER_USERNAME"/"$SERVICE_NAME":"$TRAVIS_BUILD_ID";
